server:
  port: 0
spring:
  application:
    name: mysqlservice  #全部小写
#####################################################################################################
# mysql 属性配置
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.63.125:3306/mall?useSSL=false
    username: tradewrite
    password: tradewrite
# mybatis mapper xml 配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://192.168.62.204:8880/eureka/
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  #type-aliases-package: com.microshop.servicedao.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#####################################################################################################







